name: test_task_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  injectable: ^2.1.0
  flutter_svg: ^2.0.0
  auto_route: ^7.4.0
  easy_localization: ^3.0.2
  get_it: ^7.2.0
  dio: ^5.1.2
  flutter_bloc: ^8.1.3
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  logger: ^1.1.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.0
  build_runner: ^2.3.3
  auto_route_generator: ^7.1.1
  injectable_generator: ^2.1.3

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/nav_bar/
    - assets/images/
    - assets/fonts/
    - assets/strings/
  fonts:
    - family: SF
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
